---
title: "combining exit tickets"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

# Loading and setting up

```{r}
library(tidyverse)
library(here)
library(dplyr)
library(plyr)
library(ggplot2)
library(janitor)
```

# Reading data

```{r}
#eoc1 <- read_csv(here::here("data", "eoc-1.csv"))
#eoc3 <- read_csv(here::here("data", "eoc-3.csv"))
#eoc4 <- read_csv(here::here("data", "eoc-4.csv"))
#eoc5 <- read_csv(here::here("data", "eoc-5.csv"))
#pre <- read.csv(here::here("data", "pre-survey.csv"))
#post <- read.csv(here::here("data", "post-survey.csv"))
combo <- read_csv(here::here("data", "eoc_combo.csv"))
comment <- read_csv(here::here("data", "combo_organize.csv"))
ordered <- read_csv(here::here("data", "Survey_date.csv"))
  
```

# Filtering responses

#```{r}
selected <- combo %>% 
  select("StartDate","EndDate","Progress","RecipientEmail", "ResponseId", "Survey", "Q1_1", "Q1_2", "Q1_3", "Q1_4", "Q2")%>%
  arrange(StartDate)%>%
write_csv("combo_organize.csv")
#```
```{r}
Q1_1 <- comment %>%
  select("Survey","Q1_1")%>%
  count()
```
```{r}
Q1_2 <- comment %>%
  select("Survey","Q1_2")%>%
  count()
```
```{r}
Q1_3 <- comment %>%
  select("Survey","Q1_3")%>%
  count()
```
```{r}
Q1_4 <- comment %>%
  select("Survey","Q1_4")%>%
  count()
```
```{r}
Q2 <- comment %>%
  select("Survey","Q2")%>%
  count()
```
```{r}
Q2_comments <- comment %>%
  select("Survey","Q2_code")%>%
  count()
```
```{r}
dates <- comment %>%
  select("Survey", "EndDate")%>%
  count()
  
  
```

##Breakdown Question by time points


```{r}
time_Q1_1 <- comment %>%
  janitor::tabyl(EndDate, Q1_1)
```

```{r}
time_Q1_2 <- comment %>%
  janitor::tabyl(EndDate, Q1_2)
```

```{r}
time_Q1_3 <- comment %>%
  janitor::tabyl(EndDate, Q1_3)
```

```{r}
time_Q1_4 <- comment %>%
  janitor::tabyl(EndDate, Q1_4)
```


```{r}
time_Q2 <- comment %>%
  janitor::tabyl(EndDate, Q2_code)
```














